<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 5 Activities (Correlation in R)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Week5_Activities_files/libs/clipboard/clipboard.min.js"></script>
<script src="Week5_Activities_files/libs/quarto-html/quarto.js"></script>
<script src="Week5_Activities_files/libs/quarto-html/popper.min.js"></script>
<script src="Week5_Activities_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Week5_Activities_files/libs/quarto-html/anchor.min.js"></script>
<link href="Week5_Activities_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Week5_Activities_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Week5_Activities_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Week5_Activities_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Week5_Activities_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 5 Activities (Correlation in R)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this weeks workshop, we are going to learn how to perform correlations (simple and multiple) which you covered in last weeks lecture, along with checking the relevant assumptions etc.</p>
<p><img src="Corrs.png" class="img-fluid"></p>
<p>- Use the <code>jmv</code> package to run descriptive statistics and check assumptions.</p>
<p>- Conduct a simple correlation in R.</p>
<p>- Conduct a multiple correlation R.</p>
<p>- Learn how to make pretty correlation graphs.</p>
<p>- Conduct an apriori power analysis in R for correlations.</p>
<section id="lets-get-set-up" class="level2">
<h2 class="anchored" data-anchor-id="lets-get-set-up">Let’s Get Set Up</h2>
<p>Let’s begin by ensuring your working environment is ready for today’s session. Open RStudio or Posit Cloud and complete the following tasks to set everything up.</p>
</section>
<section id="activity-1-set-up-your-working-directory-r-script-for-this-week" class="level2">
<h2 class="anchored" data-anchor-id="activity-1-set-up-your-working-directory-r-script-for-this-week">Activity 1: Set Up Your Working Directory &amp; R Script for this week</h2>
<p>One of the first steps in each of these workshops is setting up your *working directory*. The working directory is the default folder where R will look to import files or save any files you export.</p>
<p>If you don’t set the working directory, R might not be able to locate the files you need (e.g., when importing a dataset) or you might not know where your exported files have been saved. Setting the working directory beforehand ensures that everything is in the right place and avoids these issues.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reminder on Steps to Set Up Your Working Directory
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Click:<br>
<strong>Session → Set Working Directory → Choose Directory</strong></p></li>
<li><p>Navigate to the folder you created for this course (this should be the same folder you used for previous workshops).</p></li>
<li><p>Create a new folder called <code>week5</code> inside this directory.</p></li>
<li><p>Select the <code>week5</code> folder and click <strong>Open</strong>.</p></li>
</ol>
<p>Don’t forget to verify your working directory before we get started</p>
<p>You can always check your current working directory by typing in the following command in the console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/ryandonovan 1/Desktop/rintro/activities/week5"</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>As in previous weeks we will create an <strong>R script</strong> that we can use for today’s activities. This week we can call our script <code>05-correlations</code></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reminder on creating an R script
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Go to the menu bar and select:<br>
<strong>File → New File → R Script</strong></p>
<p>This will open an untitled R script.</p></li>
<li><p>To save and name your script, select:</p>
<p><strong>File→ Save As</strong>, then enter the name:</p>
<p><code>05-correlations</code></p>
<p>Click <strong>Save</strong></p></li>
</ol>
</div>
</div>
</div>
<p>At the top of your R script type in and run the following code (this turns off scientific notation from your output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="activity-2-installing-loading-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="activity-2-installing-loading-r-packages">Activity 2: Installing / Loading R Packages</h2>
<p>We’ll be using several <strong>R packages</strong> to make our analysis easier. The <code>jmv</code> package is particularly helpful for running descriptive statistics, while <code>pwr</code> helps us calculate power for our tests. The <code>car</code> package will allow us to check additional assumptions. We will be using a new package this week also: <code>correlation</code>, this package will be used for running our correlations.</p>
<p><strong>REMEMBER</strong>: If you encounter an error message like “<code>Error in library(package name): there is no packaged calledpackage name</code>”, you’ll need to install the package first by editing the following for your console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"package name"</span>) <span class="co">#replace "package name" with the actual package name</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the packages we will be using today:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv) <span class="co"># this will help us run descriptive statistics </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'jmv' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr) <span class="co"># this will enable us to conduct power analysis  </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># this is for checking assumptions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(correlation) <span class="co">#this runs our correlation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'correlation' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co"># this helps with our assumption checks</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'performance' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych) <span class="co"># this will be helpful for our multiple correlation graph</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:jmv':

    pca, reliability</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># we will be useful for making lots of pretty graphs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggplot2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:psych':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot) <span class="co"># we will be useful for making lots of pretty graphs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="activity-3-download-and-load-in-your-dataset" class="level2">
<h2 class="anchored" data-anchor-id="activity-3-download-and-load-in-your-dataset">Activity 3: Download and load in your dataset</h2>
<p>Today we are going to analyse data from a study on sleep quality, personality factors, and psychological wellbeing which you will find it on Canvas under the Module <strong>Week 5</strong></p>
<p>- <strong>SleepQuality.csv</strong> <strong>→</strong> our dataset</p>
<section id="download-this-file-onto-your-computer-and-move-it-to-your-week5-folder." class="level3">
<h3 class="anchored" data-anchor-id="download-this-file-onto-your-computer-and-move-it-to-your-week5-folder.">Download this file onto your computer and move it to your <code>week5</code> folder.</h3>
<p>Once this is done load the dataset into R and save it as a dataframe called “df_sleep”:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SleepQuality.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="correlations" class="level2">
<h2 class="anchored" data-anchor-id="correlations">Correlations</h2>
<p>Todays data was collected from a cross-sectional study examining the relationship between sleep difficulty, anxiety, and depression.</p>
<p>After loading the datasets, it’s always good practice to inspect it before doing any analyses. You can use the <code>head()</code> function to get an overview of the sleep quality dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Participant SleepDifficulty  Optimism Depression  Anxiety
1           1        12.32332  6.895218   25.73838 50.14666
2           2        12.03404 12.593687   26.36019 50.59385
3           3        12.05411  5.389429   27.75646 50.47726
4           4        13.47842  9.192558   25.01543 53.32908
5           5        16.32334  5.869162   32.23879 70.42495
6           6        18.55490  5.819719   36.75899 73.08169</code></pre>
</div>
</div>
<p>Now that our environment is set up and our dataset is loaded, we are ready to dive into descriptive statistics &amp; check our assumptions.</p>
<p>Last week we learned how to use <code>descriptives</code> function to do both of these things.</p>
</section>
<section id="activity-4-get-descriptive-statistics-check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="activity-4-get-descriptive-statistics-check-assumptions">Activity 4: Get descriptive statistics &amp; check assumptions</h2>
<p>Let’s imagine we’re interested in investigating the relationship between <strong>depression</strong> and <strong>anxiety</strong>. Specifically we predict that higher levels of depression (as shown by higher scores) will be associated with higher anxiety levels (as shown by higher scores).</p>
<p>In this case:</p>
<p>Our <strong>variables</strong> are 1) depression and 2) anxiety</p>
<p>We could specify our hypothesis as such:</p>
<p><strong>H1:</strong> We predict that higher depression will be positively correlated with higher anxiety scores.</p>
<p><strong>H0 (Null hypothesis):</strong> There will not be a significant correlation between depression scores and anxiety scores</p>
<p>Note that as we do specify the direction of the association / correlation that this is a <strong>directional hypothesis</strong></p>
<p>As we are interested in the relationship between two continuous variables, this would be best addressed via a <strong>simple correlation</strong>. Before we can do this, there are a couple of preliminary steps we need to take. First, we need to check the assumptions required for a correlation.</p>
<section id="checking-our-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="checking-our-assumptions">Checking our assumptions</h3>
<p>There are two main types of correlation you might use: <strong>Pearsons</strong> and <strong>Spearmans</strong> , for an overview of both check the associated textbook chapter on correlations. For the purposes of this workshop, you would typically use <strong>Pearsons</strong> correlation, unless the below assumptions are not met.</p>
<p>There are several key assumptions for conducting Pearsons simple correlation:</p>
<p>a. The data are continuous, and are either interval or ratio.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Interval data</strong> = Data that is measured on a numeric scale with equal distance between adjacent values, that does <strong>not</strong> have a true zero. This is a very common data type in research (e.g.&nbsp;Test scores, IQ etc).</p>
<p><strong>Ratio data</strong> = Data that is measured on a numeric scale with equal distance between adjacent values, that has a true zero (e.g.&nbsp;Height, Weight etc).</p>
<p>Here we know our two variables are outcomes on a wellbeing test, as such they are interval data and this assumption has been met</p>
</div>
</div>
</div>
<p>b. There is a data point for each participant for both variables.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A quick way to check this assumption is to see if there is any missing data. If there isn’t then this assumption is met. Note that number of missing data points is one of the values you automatically get when using the descriptives function.</p>
</div>
</div>
</div>
<p>c. The data are normally distributed for your two variables.</p>
<p>d. The relationship between the two variables is linear.</p>
<p>e. The assumption of homoscedasticity.</p>
<p><strong>Assumptions (c-d): Normality &amp; linearity</strong></p>
<p>For correlations we can check these assumptions via visualization. Please refer to the associated textbook chapter for detailed guidance on checking these assumptions via visualization.</p>
<p>Normality can be assessed using a histogram and qqplot (both of with we can get using the descriptives function), and also <strong>Shapiro-Wilks test</strong> which we learned last week. We can also take this opportunity to get some of our descriptive statistics for our write-up, we need <strong>mean</strong> and <strong>standard deviation</strong> for both variables.</p>
<p>Remember if you type <code>?descriptives</code> into your console it will give you an overview of the arguments you can use.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code in case you get stuck / to double check your work
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(df_sleep, <span class="co"># our data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">"Depression"</span>, <span class="st">"Anxiety"</span>), <span class="co"># our two variables</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>, <span class="co"># this generates a histogram</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">sw =</span> <span class="cn">TRUE</span>, <span class="co"># this runs shapiro-wilks test</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">qq=</span><span class="cn">TRUE</span>) <span class="co"># this generates a qq plot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                      
 ───────────────────────────────────────────────── 
                         Depression    Anxiety     
 ───────────────────────────────────────────────── 
   N                            150          150   
   Missing                        0            0   
   Mean                    25.05236     50.30168   
   Median                  25.14149     50.21348   
   Standard deviation      6.173965     12.34318   
   Minimum                 8.203621     16.32001   
   Maximum                 40.04161     78.15740   
   Shapiro-Wilk W         0.9942665    0.9914144   
   Shapiro-Wilk p         0.8206004    0.5009269   
 ───────────────────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>To check for linearity can use a scatterplot. The below code will generate a simple scatterplot for this purpose of checking normality (later on we’ll learn to generate prettier graphs that you can use in your reports).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>df_sleep<span class="sc">$</span>Depression,<span class="at">y=</span>df_sleep<span class="sc">$</span>Anxiety)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>e.</strong> <strong>Homoscedasticity</strong></p>
<p>There are a number of ways to check this assumption: visually via plotting of the residuals (which we will cover in Week 7 for Regression), or via a test. Here we will use a Breusch-Pagan test (1979) for heteroscedasticity.</p>
<p>To do this we will create a linear model, and then use the function <code>check_heteroscasticity</code> from the performance package.</p>
<p>If we get a non-significant p-value then the data is homoscedastic and our assumption has been met.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Depression <span class="sc">~</span> Anxiety, <span class="at">data =</span> df_sleep) <span class="co"># here we are creating an object "model" which contatins a linear model of our DV ~ IV </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(model) <span class="co"># this function performs a Breusch-Pagan test for our model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.771).</code></pre>
</div>
</div>
<p>Based on the above we can ascertain that:</p>
<ul>
<li><p>the variables are normally distributed</p></li>
<li><p>the relationship between the two variables is linear</p></li>
<li><p>the assumption of homoscedasticity is met</p></li>
</ul>
<p>As such we can use a <strong>Pearson</strong> correlation to test our hypotheses.</p>
</section>
</section>
<section id="activity-5-running-the-simple-correlation" class="level2">
<h2 class="anchored" data-anchor-id="activity-5-running-the-simple-correlation">Activity 5: Running the Simple Correlation</h2>
<p>We use the <code>correlation</code> function to perform the correlation. The syntax is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember you need to edit the specific names/variables below to make it work for our data and needs</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(DataframeName<span class="sc">$</span>Variable1, DataframeName<span class="sc">$</span>Variable2, <span class="at">method =</span> <span class="st">"pearson"</span> OR <span class="st">"spearman"</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span> or <span class="st">"less"</span> or <span class="st">"greater"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative specifies whether it's a one or two-sided test, or one-sided. "greater" corresponds to positive association, "less" to negative association</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we have a <strong>directional hypothesis</strong> where we expect a <strong>positive</strong> correlation we will run a one-sided correlation. Let’s run this correlation for depression and anxiety on our <code>df_sleep</code> dataset:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Our simple correlation code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df_sleep<span class="sc">$</span>Depression, df_sleep<span class="sc">$</span>Anxiety, <span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  df_sleep$Depression and df_sleep$Anxiety
t = 56.595, df = 148, p-value &lt; 0.00000000000000022
alternative hypothesis: true correlation is greater than 0
95 percent confidence interval:
 0.9708085 1.0000000
sample estimates:
     cor 
0.977668 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The correlation results show a significant correlation between the depression and anxiety scores.</p>
<p><strong>Here’s how we might write up the results in APA style:</strong></p>
<p>A Pearsons correlation was conducted to assess the relationship between depression (<em>M</em>= 25.05, <em>SD</em>= 6.17) and anxiety scores (<em>M</em>= 50.3, <em>SD</em>= 12.34). The test showed that there was a significant positive correlation between the two variables <em>r</em>(148) = 0.98, <em>p</em> &lt; 0.01. As such we reject the null hypothesis.</p>
</section>
<section id="multiple-correlations" class="level2">
<h2 class="anchored" data-anchor-id="multiple-correlations">Multiple Correlations</h2>
<p>Sometimes we’re interested in the associations between multiple variables. In todays dataset we have sleep difficulty, optimism, depression, and anxiety. As such we might be interested in the relationship between all four variables.</p>
<p>In addition to our earlier prediction regarding depression and anxiety we could also predict:</p>
<p>1) that greater sleep difficulty (as shown by higher values) will be associated with higher anxiety and depression levels (as shown by higher scores).</p>
<p>2) that greater optimism (as shown by higher values) will be associated with lower anxiety and depression levels (as shown by lower scores).</p>
<p>In this case:</p>
<p>Our <strong>variables</strong> are 1) depression, 2) anxiety, 3) sleep difficulty, and 4) optimism.</p>
<p>As we are interested in the relationship between four continuous variables, this would be best addressed via a <strong>multiple correlation</strong>. Before we can do this, there are a couple of preliminary steps we need to take.</p>
<p>A lot of the steps are very similar to a simple correlation. So we can refer to the above sections for help if we get unsure.</p>
</section>
<section id="activity-6-descriptive-statistics-and-assumption-checking" class="level2">
<h2 class="anchored" data-anchor-id="activity-6-descriptive-statistics-and-assumption-checking">Activity 6: Descriptive statistics and assumption checking</h2>
<p>We already checked that depression and anxiety meet the assumptions for a Pearsons correlation but now we need to do the same for <strong>sleep difficulty</strong> and <strong>optimism</strong>. Double-check <strong>Activity 4</strong> for a reminder on the steps to check the below.</p>
<p>a. The data are continuous, and are either interval or ratio.</p>
<p>b. There is a data point for each participant for both variables.</p>
<p>c. The data are normally distributed for your two variables.</p>
<p>d. The relationship between the two variables is linear.</p>
<p>e. The assumption of homoscedasticity.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code to double-check your work when you’re done
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(df_sleep, <span class="co"># our data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">"Depression"</span>, <span class="st">"Anxiety"</span>, <span class="st">"SleepDifficulty"</span>, <span class="st">"Optimism"</span>), <span class="co"># our four variables</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>, <span class="co"># this generates a histogram</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">sw =</span> <span class="cn">TRUE</span>, <span class="co"># this runs shapiro-wilks test</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">qq=</span><span class="cn">TRUE</span>) <span class="co"># this generates a qq plot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                                                      
 ───────────────────────────────────────────────────────────────────────────────── 
                         Depression    Anxiety      SleepDifficulty    Optimism    
 ───────────────────────────────────────────────────────────────────────────────── 
   N                            150          150                150          150   
   Missing                        0            0                  0            0   
   Mean                    25.05236     50.30168           12.37026     10.57763   
   Median                  25.14149     50.21348           12.37819     10.76353   
   Standard deviation      6.173965     12.34318           2.736946     3.284548   
   Minimum                 8.203621     16.32001           6.599527    0.4951533   
   Maximum                 40.04161     78.15740           18.73516     18.83997   
   Shapiro-Wilk W         0.9942665    0.9914144          0.9846297    0.9912025   
   Shapiro-Wilk p         0.8206004    0.5009269          0.0937667    0.4788844   
 ───────────────────────────────────────────────────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-12-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to try the pairs.panel function it enables you to check the visual assumptions for all the variables at once.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs.panels</span>(df_sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="activity-7-running-the-multiple-correlation" class="level2">
<h2 class="anchored" data-anchor-id="activity-7-running-the-multiple-correlation">Activity 7: Running the multiple correlation</h2>
<p>To run our multiple correlation we need to use slightly different syntax than before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember you need to edit the specific names/variables below to make it work for our data and needs</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">correlation</span>(DataframeName, <span class="co"># our data</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">select =</span> <span class="fu">c</span>(<span class="st">"Variable1"</span>, <span class="st">"Variable2"</span>, <span class="st">"Variable3"</span>, <span class="st">"Variable4"</span>), <span class="co"># our variables</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">"pearson"</span> OR <span class="st">"spearman"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">p_adjust =</span> <span class="st">"bonferroni"</span>) <span class="co"># our bonferroni adjustment for multiple comparisons - see the associated textbook chapter for a discussion of this</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that we do not specify the direction of our predicted correlation here as some may be positive and others may be negative</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code to double-check your work when you’re done
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we are saving the results of our correlation as an object called "mcor"</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>mcor <span class="ot">&lt;-</span> <span class="fu">correlation</span>(df_sleep, <span class="co"># our data</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">select =</span> <span class="fu">c</span>(<span class="st">"Depression"</span>, <span class="st">"Anxiety"</span>, <span class="st">"SleepDifficulty"</span>, <span class="st">"Optimism"</span>), <span class="co"># our variables</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">"pearson"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">p_adjust =</span> <span class="st">"bonferroni"</span>) <span class="co"># our bonferroni adjustment for multiple comparisons</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>mcor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Correlation Matrix (pearson-method)

Parameter1      |      Parameter2 |     r |         95% CI | t(148) |         p
-------------------------------------------------------------------------------
Depression      |         Anxiety |  0.98 | [ 0.97,  0.98] |  56.60 | &lt; .001***
Depression      | SleepDifficulty |  0.90 | [ 0.87,  0.93] |  25.65 | &lt; .001***
Depression      |        Optimism | -0.16 | [-0.31,  0.00] |  -1.98 | 0.298    
Anxiety         | SleepDifficulty |  0.88 | [ 0.84,  0.91] |  22.47 | &lt; .001***
Anxiety         |        Optimism | -0.14 | [-0.29,  0.02] |  -1.73 | 0.515    
SleepDifficulty |        Optimism | -0.10 | [-0.25,  0.06] |  -1.18 | &gt; .999   

p-value adjustment method: Bonferroni
Observations: 150</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>How we might write up the results in APA style?</strong></p>
<p>A Pearsons multiple correlation with bonferroni correction was conducted to assess the relationship between depression (<em>M</em>= 24.26, <em>SD</em>= 5.89), anxiety scores (<em>M</em>= 48.62, <em>SD</em>= 12.48), sleep difficulty (<em>M</em>= <strong>?</strong>, <em>SD</em>= <strong>?</strong>), and optimism (<em>M</em>= <strong>?</strong>, <em>SD</em>= <strong>?</strong>). The test showed that there was a significant positive correlation between depression and anxiety <em>r</em>(148) = 0.97, <em>p</em> &lt; 0.01, and depression and sleep difficulty <em>r</em>(148) = 0.9, <em>p</em> &lt; 0.01, but no significant correlation between depression and optimism <em>r</em>(148) = -0.16, <em>p</em> = 0.29<strong>.</strong> There was also a significant positive correlation between anxiety and sleep difficulty <em>r</em>(148) = 0.88, <em>p</em> &lt; 0.01, but no significant correlation between optimism and anxiety <em>r</em>(148) = -0.14, <em>p</em> = 0.52 or optimism and sleep difficulty <em>r</em>(148) = -0.1, <em>p</em> = &gt;.99.</p>
</section>
<section id="activity-8-graphs" class="level2">
<h2 class="anchored" data-anchor-id="activity-8-graphs">Activity 8: Graphs</h2>
<p>We need to visualize our data not only to check our assumptions but also to include in our write-up / results / dissertations. As you may see above the write-up for a multiple correlation can be lengthy/confusing, and a good graphic can help your reader (and you) understand the results more easily.</p>
<p>Today we’ll be using the <code>ggcorrplot</code> function. We will learn a lot more about making visualizations in week 9, but for today we will learn how to clearly visualize our correlation results. The code below makes a correlation matrix for the multiple correlation we just ran.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(mcor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If you type in <code>?ggcorrplot</code> to your console you can see there are many optional arguments you can use to customize your graph. Using this try to do the following:</p>
<ol type="1">
<li>Give your graph a meaningful title (e.g.&nbsp;“Super cool correlation matrix”)</li>
<li>Try changing the display type lower and upper, see what looks best.</li>
<li>Display the correlation values on the graph</li>
<li>Try changing method to “circle”</li>
<li>Try some of the arguments, see what you think looks best</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ciara’s attempt at “super cool correlation matrix” code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(mcor, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">title =</span> <span class="st">"Super cool correlation matrix"</span>,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">lab =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week5_Activities_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>You may also want to save your graphs outside of R (e.g.&nbsp;to use in a report or paper). There are a few ways to do this.</p>
<ol type="1">
<li>To simply export from the “Plots” panel in R (as below).</li>
</ol>
<p><img src="ExportImage.gif" class="img-fluid"></p>
<ol start="2" type="1">
<li>To export via code as below:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">png</span>(<span class="st">"myplot.png"</span>)  <span class="co">#specify you want a png file, and your file name</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>myplot <span class="ot">&lt;-</span> <span class="fu">ggcorrplot</span>(mcor) <span class="co"># create an object with that same name that is your plot</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(myplot) <span class="co"># print the plot</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>() <span class="co"># #this tells R that we are done with adding stuff to our png</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quartz_off_screen 
                2 </code></pre>
</div>
</div>
</section>
<section id="activity-9-power-analyses" class="level2">
<h2 class="anchored" data-anchor-id="activity-9-power-analyses">Activity 9: Power analyses!</h2>
<p>Here we are going to learn about how to conduct a power analysis for a correlation.</p>
<p>As you may recall there are some key pieces of information we need for a power analysis, and some specifics that we need for a correlation:</p>
<ol type="1">
<li><p>Alpha level (typically 0.05 in Psychology and the social sciences)</p></li>
<li><p>The minimum correlation size of interest</p></li>
<li><p>Our desired power</p></li>
<li><p>If our test is one or two-tailed (i.e.&nbsp;do we have a directional or nondirectional hypothesis)</p></li>
</ol>
<p>Reminder that this <a href="https://rpsychologist.com/d3/nhst/">interactive visualization</a> can be helpful in understanding how these things interact.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How do I know what the minimum correlation size of interest is?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is a good question! Correlation (r) values can be split into arbitrary bands as shown below (Cohen, 1988):</p>
<ul>
<li><p>Small Effect (r = ~ 0.1)</p></li>
<li><p>Medium Effect (r = ~ 0.3)</p></li>
<li><p>Large Effect (r = ~ 0.5)</p></li>
</ul>
<p>As we are aware it is easier to detect large effects. As such, if we really have no idea what effect size we should expect then we should power for small effects.</p>
<p>If however we are conducting a replication, or a very similar study to one that has been already done, then we can power for the correlation they report.</p>
<p>Again I refer to: <a href="https://online.ucpress.edu/collabra/article/8/1/33267/120491/Sample-Size-Justification">A useful paper if you’re interested in learning more</a></p>
</div>
</div>
</div>
</section>
<section id="power-analysis-for-a-simple-correlation" class="level2">
<h2 class="anchored" data-anchor-id="power-analysis-for-a-simple-correlation">Power analysis for a simple correlation</h2>
<p>The syntax for conducting an apriori statistical power analysis for a simple correlation is the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct power analysis for a simple correlation</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.r.test</span>(<span class="at">r =</span> <span class="fl">0.2</span>, <span class="co"># your expected correlation value</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">power =</span> <span class="fl">0.80</span>, <span class="co"># Desired power level</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="at">alternative =</span> <span class="st">"two.sided"</span>) <span class="co"># Indicates a two-tailed test, #can be changed to less or greater</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     approximate correlation power calculation (arctangh transformation) 

              n = 193.0867
              r = 0.2
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
</div>
<ol type="1">
<li><p>Try running the above power-analyses again but for a one sided (directional) test. What does this do to our required sample size?</p></li>
<li><p>What happens if we increase the correlation value we expect to find?</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>