<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 8 Activities (Anova in R)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="08-workshop-activities_files/libs/clipboard/clipboard.min.js"></script>
<script src="08-workshop-activities_files/libs/quarto-html/quarto.js"></script>
<script src="08-workshop-activities_files/libs/quarto-html/popper.min.js"></script>
<script src="08-workshop-activities_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="08-workshop-activities_files/libs/quarto-html/anchor.min.js"></script>
<link href="08-workshop-activities_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08-workshop-activities_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="08-workshop-activities_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="08-workshop-activities_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="08-workshop-activities_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setting-up-r" id="toc-setting-up-r" class="nav-link active" data-scroll-target="#setting-up-r">Setting Up R</a>
  <ul>
  <li><a href="#activity-1-set-up-your-working-directory-r-script" id="toc-activity-1-set-up-your-working-directory-r-script" class="nav-link" data-scroll-target="#activity-1-set-up-your-working-directory-r-script">Activity 1: Set Up Your Working Directory &amp; R Script</a></li>
  <li><a href="#activity-2-installing-loading-r-packages" id="toc-activity-2-installing-loading-r-packages" class="nav-link" data-scroll-target="#activity-2-installing-loading-r-packages">Activity 2: Installing / Loading R Packages</a></li>
  <li><a href="#activity-3-load-your-datasets" id="toc-activity-3-load-your-datasets" class="nav-link" data-scroll-target="#activity-3-load-your-datasets">Activity 3: Load Your Datasets</a></li>
  </ul></li>
  <li><a href="#one-way-anova---example-exercise" id="toc-one-way-anova---example-exercise" class="nav-link" data-scroll-target="#one-way-anova---example-exercise">One Way ANOVA - Example &amp; Exercise</a>
  <ul>
  <li><a href="#activity-4-one-way-between-subjects-anova-example" id="toc-activity-4-one-way-between-subjects-anova-example" class="nav-link" data-scroll-target="#activity-4-one-way-between-subjects-anova-example">Activity 4: One-Way Between Subjects ANOVA Example</a>
  <ul class="collapse">
  <li><a href="#step-1-load-in-and-check-your-dataset" id="toc-step-1-load-in-and-check-your-dataset" class="nav-link" data-scroll-target="#step-1-load-in-and-check-your-dataset">Step 1: Load in and Check your Dataset</a></li>
  <li><a href="#step-2-conduct-descriptive-statistical-analysis" id="toc-step-2-conduct-descriptive-statistical-analysis" class="nav-link" data-scroll-target="#step-2-conduct-descriptive-statistical-analysis">Step 2: Conduct Descriptive Statistical Analysis</a></li>
  <li><a href="#step-3-run-our-one-way-anova" id="toc-step-3-run-our-one-way-anova" class="nav-link" data-scroll-target="#step-3-run-our-one-way-anova">Step 3: Run our One-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#running-our-one-way-anova" id="toc-running-our-one-way-anova" class="nav-link" data-scroll-target="#running-our-one-way-anova">Running Our One-Way ANOVA</a></li>
  </ul></li>
  <li><a href="#step-4-check-parametric-assumptions" id="toc-step-4-check-parametric-assumptions" class="nav-link" data-scroll-target="#step-4-check-parametric-assumptions">Step 4: Check Parametric Assumptions</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results"><strong>Interpreting the Results</strong></a></li>
  <li><a href="#interpreting-the-results-1" id="toc-interpreting-the-results-1" class="nav-link" data-scroll-target="#interpreting-the-results-1"><strong>Interpreting the Results</strong></a></li>
  </ul></li>
  <li><a href="#step-5-running-post-hoc-tests" id="toc-step-5-running-post-hoc-tests" class="nav-link" data-scroll-target="#step-5-running-post-hoc-tests">Step 5: Running post-hoc tests</a>
  <ul class="collapse">
  <li><a href="#post-hoc-test-syntax" id="toc-post-hoc-test-syntax" class="nav-link" data-scroll-target="#post-hoc-test-syntax"><strong>Post-Hoc Test Syntax</strong></a></li>
  <li><a href="#running-the-post-hoc-test-on-our-data" id="toc-running-the-post-hoc-test-on-our-data" class="nav-link" data-scroll-target="#running-the-post-hoc-test-on-our-data">Running the Post-Hoc Test on Our Data</a></li>
  </ul></li>
  <li><a href="#step-6-writing-our-results-in-apa-style" id="toc-step-6-writing-our-results-in-apa-style" class="nav-link" data-scroll-target="#step-6-writing-our-results-in-apa-style">Step 6: Writing our results in APA style</a></li>
  <li><a href="#step-7-power-analysis" id="toc-step-7-power-analysis" class="nav-link" data-scroll-target="#step-7-power-analysis">Step 7: Power Analysis</a>
  <ul class="collapse">
  <li><a href="#apriori-power-analysis" id="toc-apriori-power-analysis" class="nav-link" data-scroll-target="#apriori-power-analysis"><strong>Apriori Power Analysis</strong></a></li>
  <li><a href="#post-hoc-power-analysis" id="toc-post-hoc-power-analysis" class="nav-link" data-scroll-target="#post-hoc-power-analysis">Post-Hoc Power Analysis</a></li>
  </ul></li>
  <li><a href="#step-8-create-a-nice-visualisation-violin-plot" id="toc-step-8-create-a-nice-visualisation-violin-plot" class="nav-link" data-scroll-target="#step-8-create-a-nice-visualisation-violin-plot">Step 8: Create a Nice Visualisation (Violin Plot)</a></li>
  </ul></li>
  <li><a href="#activity-5-one-way-anova-exercise" id="toc-activity-5-one-way-anova-exercise" class="nav-link" data-scroll-target="#activity-5-one-way-anova-exercise">Activity 5: One-Way ANOVA Exercise</a></li>
  </ul></li>
  <li><a href="#factorial-anova" id="toc-factorial-anova" class="nav-link" data-scroll-target="#factorial-anova">Factorial ANOVA</a>
  <ul>
  <li><a href="#activity-6-factorial-anova-example" id="toc-activity-6-factorial-anova-example" class="nav-link" data-scroll-target="#activity-6-factorial-anova-example">Activity 6: Factorial ANOVA Example</a>
  <ul class="collapse">
  <li><a href="#research-introduction" id="toc-research-introduction" class="nav-link" data-scroll-target="#research-introduction">Research Introduction</a></li>
  <li><a href="#step-1-load-in-and-check-your-data" id="toc-step-1-load-in-and-check-your-data" class="nav-link" data-scroll-target="#step-1-load-in-and-check-your-data">Step 1: Load in and Check Your Data</a></li>
  <li><a href="#step-2-conduct-descriptive-statistical-analysis-1" id="toc-step-2-conduct-descriptive-statistical-analysis-1" class="nav-link" data-scroll-target="#step-2-conduct-descriptive-statistical-analysis-1">Step 2: Conduct Descriptive Statistical Analysis</a></li>
  <li><a href="#step-3-run-your-factorial-anova" id="toc-step-3-run-your-factorial-anova" class="nav-link" data-scroll-target="#step-3-run-your-factorial-anova">Step 3: Run Your Factorial ANOVA</a>
  <ul class="collapse">
  <li><a href="#the-syntax" id="toc-the-syntax" class="nav-link" data-scroll-target="#the-syntax">The Syntax</a></li>
  <li><a href="#running-it-on-our-dataset" id="toc-running-it-on-our-dataset" class="nav-link" data-scroll-target="#running-it-on-our-dataset">Running it on our Dataset</a></li>
  </ul></li>
  <li><a href="#step-4-check-your-parametric-assumptions" id="toc-step-4-check-your-parametric-assumptions" class="nav-link" data-scroll-target="#step-4-check-your-parametric-assumptions">Step 4: Check Your Parametric Assumptions</a></li>
  <li><a href="#step-5-run-your-post-hoc-comparisons" id="toc-step-5-run-your-post-hoc-comparisons" class="nav-link" data-scroll-target="#step-5-run-your-post-hoc-comparisons">Step 5: Run Your Post-Hoc Comparisons</a>
  <ul class="collapse">
  <li><a href="#main-findings" id="toc-main-findings" class="nav-link" data-scroll-target="#main-findings"><strong>Main Findings</strong></a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><strong>Summary</strong></a></li>
  </ul></li>
  <li><a href="#step-6-visualise-your-model" id="toc-step-6-visualise-your-model" class="nav-link" data-scroll-target="#step-6-visualise-your-model">Step 6: Visualise your Model</a></li>
  <li><a href="#step-7-write-up-your-results-in-apa-style" id="toc-step-7-write-up-your-results-in-apa-style" class="nav-link" data-scroll-target="#step-7-write-up-your-results-in-apa-style">Step 7: Write up your results in APA style</a></li>
  </ul></li>
  <li><a href="#activity-7-factorial-anova-exercise" id="toc-activity-7-factorial-anova-exercise" class="nav-link" data-scroll-target="#activity-7-factorial-anova-exercise">Activity 7: Factorial ANOVA Exercise</a>
  <ul class="collapse">
  <li><a href="#research-introduction-1" id="toc-research-introduction-1" class="nav-link" data-scroll-target="#research-introduction-1"><strong>Research Introduction</strong></a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><strong>Research Question</strong></a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><strong>Hypotheses</strong></a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method"><strong>Method</strong></a></li>
  <li><a href="#our-task" id="toc-our-task" class="nav-link" data-scroll-target="#our-task"><strong>Our Task</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="08-workshop-activities.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 8 Activities (Anova in R)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this week’s workshop, we will learn how to run a between-subjects <strong>one-way ANOVA</strong> and a between-subjects <strong>factorial ANOVA</strong> in R.</p>
<section id="setting-up-r" class="level1">
<h1>Setting Up R</h1>
<p>Before we begin, let’s ensure your working environment is ready for today’s session. Open <strong>RStudio</strong> or <strong>Posit Cloud</strong>, and follow the steps below.</p>
<section id="activity-1-set-up-your-working-directory-r-script" class="level2">
<h2 class="anchored" data-anchor-id="activity-1-set-up-your-working-directory-r-script">Activity 1: Set Up Your Working Directory &amp; R Script</h2>
<p>Each time we work in R, it’s important to set up our <strong>working directory</strong>. This is the folder where R looks for files when importing data and where it saves any files you export.</p>
<p>If you don’t set the working directory, R may not be able to locate your dataset, or you might not know where your exported files have been saved. Setting the working directory beforehand helps keep everything organised and prevents these issues.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reminder on Steps to Set Up Your Working Directory
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Click:<br>
<strong>Session → Set Working Directory → Choose Directory</strong></p></li>
<li><p>Navigate to the folder you created for this course (this should be the same folder you used for previous workshops).</p></li>
<li><p>Create a new folder called <code>week8</code> inside this directory.</p></li>
<li><p>Select the <code>week8</code> folder and click <strong>Open</strong>.</p></li>
</ol>
<p>Don’t forget to verify your working directory before we get started</p>
<p>You can always check your current working directory by typing in the following command in the console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/0131045s/Desktop/Programming/R/Workshops/rintro/activities/week8"</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>As in previous weeks we will create an <strong>R script</strong> that we can use for today’s activities. This week we’ll name the script as <code>08-anova</code></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reminder on creating an R script
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Go to the menu bar and select:<br>
<strong>File → New File → R Script</strong></p>
<p>This will open an untitled R script.</p></li>
<li><p>To save and name your script, select:</p>
<p><strong>File→ Save As</strong>, then enter the name:</p>
<p><code>08-anova</code></p>
<p>Click <strong>Save</strong></p></li>
</ol>
</div>
</div>
</div>
<p>At the top of your R script type in and run the following code (this turns off scientific notation from your output):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="activity-2-installing-loading-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="activity-2-installing-loading-r-packages">Activity 2: Installing / Loading R Packages</h2>
<p>We will use several R packages to simplify our analysis. Ensure you have them installed and loaded.</p>
<p><strong>REMEMBER</strong>: If you encounter an error message like “<code>Error in library(package name): there is no packaged calledpackage name</code>”, you’ll need to install the package first by editing the following for your console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"package name"</span>) <span class="co">#replace "package name" with the actual package name</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the packages we will be using today. Make sure that you have loaded in each of these packages by running the following lines of code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#helps build useful plots</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co">#for checking assumptions</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex) <span class="co">#For running our ANOVA models</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#Data manipulation</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr) <span class="co">#power analysis</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr) <span class="co">#effect size calculations</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) <span class="co">#Computes post-hoc tests</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#Assesses models performances and assumptions</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv) <span class="co">#Descriptive statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="activity-3-load-your-datasets" class="level2">
<h2 class="anchored" data-anchor-id="activity-3-load-your-datasets">Activity 3: Load Your Datasets</h2>
<p>This week, we will work with <strong>four separate datasets</strong>. You can find these datasets on <strong>Canvas</strong>.</p>
<ul>
<li><strong><code>psycho.csv</code></strong> → Dataset for the <strong>One-Way ANOVA Example</strong><br>
</li>
<li><strong><code>caffeine_mood.csv</code></strong> → Dataset for the <strong>One-Way ANOVA Exercise</strong><br>
</li>
<li><strong><code>anxiety_treatment.csv</code></strong> → Dataset for the <strong>Factorial ANOVA Example</strong><br>
</li>
<li><strong><code>diet_exercise.csv</code></strong> → Dataset for the <strong>Factorial ANOVA Exercise</strong></li>
</ul>
<p><strong><em>Download these files onto your computer and move them to your <code>week8</code> folder.</em></strong></p>
</section>
</section>
<section id="one-way-anova---example-exercise" class="level1">
<h1>One Way ANOVA - Example &amp; Exercise</h1>
<section id="activity-4-one-way-between-subjects-anova-example" class="level2">
<h2 class="anchored" data-anchor-id="activity-4-one-way-between-subjects-anova-example">Activity 4: One-Way Between Subjects ANOVA Example</h2>
<p>In recent years, there has been a growing interest in exploring the therapeutic potential of psychoactive treatments for mental health. This dataset examines the effects of Psilocybin and DMT on Neuroticism, a personality trait associated with various psychological disorders. The researchers investigated whether the administration of Psilocybin and DMT had a significant effect on participants’ Neuroticism levels.</p>
<p><strong><em>Research Question</em></strong>: Is there an effect of psychoactive treatment on Neuroticism?</p>
<p><strong>Hypotheses</strong>:</p>
<p><em>H₀ (Null Hypothesis)</em><strong>:</strong> There is no effect of psychoactive treatment on Neuroticism.</p>
<p><em>H₁ (Alternative Hypothesis):</em> There is an effect of psychoactive treatment on Neuroticism.</p>
<p><strong><em>Method</em></strong>: 60 participants were recruited and randomly assigned to one of three groups: Psilocybin, DMT, or Placebo. One-day after taking the substance, participants completed a Neuroticism Measure.</p>
<p><strong><em>Our task</em></strong>: Run a One-Way ANOVA to see if there is an effect of Psychoactive treatment on Neuroticism.</p>
<section id="step-1-load-in-and-check-your-dataset" class="level3">
<h3 class="anchored" data-anchor-id="step-1-load-in-and-check-your-dataset">Step 1: Load in and Check your Dataset</h3>
<p>First, we need to load the dataset into R using the <code>read.csv()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_psycho <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"psycho.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once a dataset is loaded, it’s important to always verify that:</p>
<ol type="1">
<li><p>It has been loaded correctly.</p></li>
<li><p>It contains the expected data.</p></li>
</ol>
<p>We can use the <code>head()</code> function to quickly check this by displaying the first 6 rows of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_psycho)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Participant_ID Treatment Neuroticism
1              1   Placebo    39.39524
2              2   Placebo    42.69823
3              3   Placebo    60.58708
4              4   Placebo    45.70508
5              5   Placebo    46.29288
6              6   Placebo    62.15065</code></pre>
</div>
</div>
<p>Another way you can quickly sanity check your dataset is by checking the last few rows with the <code>tail()</code> function. The <code>tail()</code> function works like the <code>head()</code> function, the only difference being it prints the last 6 rows of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(df_psycho)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Participant_ID  Treatment Neuroticism
55             55 Psilocybin    52.74229
56             56 Psilocybin    70.16471
57             57 Psilocybin    39.51247
58             58 Psilocybin    60.84614
59             59 Psilocybin    56.23854
60             60 Psilocybin    57.15942</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="What if I want to view the entire dataset?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What if I want to view the entire dataset?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/08-view-entire-dataset.gif" class="img-fluid figure-img"></p>
<figcaption>You can click on the dataset in the Environment page to view it</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Either way, everything looks in order, so let’s get cracking with the analysis.</p>
</section>
<section id="step-2-conduct-descriptive-statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="step-2-conduct-descriptive-statistical-analysis">Step 2: Conduct Descriptive Statistical Analysis</h3>
<p>Now, let’s run some descriptive statistics using the <code>descriptives()</code> function. This will help us understand the distribution of <strong>Neuroticism</strong> scores across the different treatment groups.</p>
<p>We will first calculate the mean, standard deviation, and other key statistics for Neuroticism, grouped by Treatment:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_psycho, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">"Neuroticism"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">"Treatment"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                        
 ─────────────────────────────────────────────────── 
                         Treatment     Neuroticism   
 ─────────────────────────────────────────────────── 
   N                     DMT                    20   
                         Placebo                20   
                         Psilocybin             20   
   Missing               DMT                     0   
                         Placebo                 0   
                         Psilocybin              0   
   Mean                  DMT              44.48743   
                         Placebo          46.41624   
                         Psilocybin       56.06485   
   Median                DMT              43.60057   
                         Placebo          46.19985   
                         Psilocybin       54.64291   
   Standard deviation    DMT              8.299387   
                         Placebo          9.726653   
                         Psilocybin       9.573406   
   Minimum               DMT              28.13307   
                         Placebo          25.33383   
                         Psilocybin       39.51247   
   Maximum               DMT              57.53815   
                         Placebo          62.86913   
                         Psilocybin       76.68956   
 ─────────────────────────────────────────────────── </code></pre>
</div>
</div>
<p>This gives us a first look at the data, but we can refine it further.</p>
<p>If you remember from week 4, we can adjust the <code>descriptives()</code> function to remove unnecessary details and add visualisations.</p>
<p>In the code below, we will:</p>
<ul>
<li><p>Remove the minimum (<code>min = FALSE</code>) and maximum (<code>max = FALSE</code>) values. I am removing both just to remove some clutter from our Descriptives output table.</p></li>
<li><p>Generate visualisations:</p>
<ul>
<li><p>A histogram (<code>hist = TRUE</code>) with a density overlay (<code>dens = TRUE</code>).</p></li>
<li><p>A bar plot (<code>bar = TRUE</code>).</p></li>
<li><p>A boxplot (<code>box = TRUE</code>) to examine distribution and possible outliers.</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_psycho, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">"Neuroticism"</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">min =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">max =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>, </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">dens =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">bar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">TRUE</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in FUN(X[[i]], ...): no non-missing arguments to max; returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                        
 ─────────────────────────────────────────────────── 
                         Treatment     Neuroticism   
 ─────────────────────────────────────────────────── 
   N                     DMT                    20   
                         Placebo                20   
                         Psilocybin             20   
   Missing               DMT                     0   
                         Placebo                 0   
                         Psilocybin              0   
   Mean                  DMT              44.48743   
                         Placebo          46.41624   
                         Psilocybin       56.06485   
   Median                DMT              43.60057   
                         Placebo          46.19985   
                         Psilocybin       54.64291   
   Standard deviation    DMT              8.299387   
                         Placebo          9.726653   
                         Psilocybin       9.573406   
 ─────────────────────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the results, we can observe the following:</p>
<ul>
<li><p>Participants in the <em>Psilocybin</em> group tend to score higher on Neuroticism than those in the <em>DMT</em> or <em>Placebo</em> groups.</p></li>
<li><p>The <em>DMT</em> and <em>Placebo</em> groups have similar Neuroticism scores.</p></li>
</ul>
<p>Now let’s investigate whether there is a significant effect of Treatment on Neuroticism.</p>
</section>
<section id="step-3-run-our-one-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="step-3-run-our-one-way-anova">Step 3: Run our One-Way ANOVA</h3>
<p>To run a <strong>one-way ANOVA</strong>, we use the <code>aov_ez()</code> function. Below is the general syntax (you will need to replace certain placeholders with the appropriate column names from your dataset):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>anova_example_syntax <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="at">id =</span> <span class="st">"The name of the Participant ID column"</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dv =</span> <span class="st">"The name of the dependent variable"</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">between =</span> <span class="st">"The name of the independent variable"</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">es =</span> <span class="st">"pes"</span>, </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">type =</span> <span class="dv">3</span>, </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">include_aov =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> yourdataset) </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova_example_syntax) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Code Explanation">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code Explanation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="code-explanation" class="level4">
<h4 class="anchored" data-anchor-id="code-explanation">Code Explanation</h4>
<p>Let’s unpack what is going on here code wise:</p>
<ol type="1">
<li><p><strong><code>anova_example_syntax &lt;- aov_ez(...)</code></strong>: This line of code is creating a new R variable called <strong><code>anova_example_syntax</code></strong>. This variable will store the results of the one-way ANOVA analysis.</p></li>
<li><p><strong><code>id = "the name of your participant ID column"</code></strong>: This part specifies the column in your dataset that contains the participant IDs. It helps identify which data points belong to each participant.</p></li>
<li><p><strong><code>dv = "the name of your your dependent variable column"</code></strong>: Here, you specify the dependent variable</p></li>
<li><p><strong><code>between = "the name of your your independent variable column"</code></strong>: Here, you specify the independent variable</p></li>
<li><p><strong><code>es = "pes"</code></strong>: This argument specifies that you want to compute the effect size in terms of partial eta-squared (<code>pes</code>).</p></li>
<li><p><strong><code>type = 3</code></strong>: The <strong><code>type</code></strong> argument specifies the type of sum of squares used in the ANOVA. Type 3 is often used for balanced designs.</p></li>
<li><p><strong><code>include_aov = TRUE</code></strong>: This indicates that you want to include the standard ANOVA table as part of the output. It provides additional information about the analysis.</p></li>
<li><p><strong><code>data = yourdataset</code></strong>: Finally, you specify the dataset on which you want to perform the ANOVA analysis.</p></li>
</ol>
</section>
<section id="understanding-the-output" class="level4">
<h4 class="anchored" data-anchor-id="understanding-the-output"><strong>Understanding the Output</strong></h4>
<ul>
<li><p>Running <strong><code>anova_example_syntax</code></strong> will display the ANOVA results, including the <em>F-statistic</em>, <em>degrees of freedom</em>, and <em>p-value</em>.</p></li>
<li><p>Running <strong><code>anova(anova_example_syntax)</code></strong> provides a more detailed table with additional information such as <em>sum of squares</em> and <em>mean squares</em>.</p></li>
<li><p>The p-value will help us determine whether the treatment groups significantly differ in Neuroticism scores.</p></li>
</ul>
</section>
</div>
</div>
</div>
<section id="running-our-one-way-anova" class="level4">
<h4 class="anchored" data-anchor-id="running-our-one-way-anova">Running Our One-Way ANOVA</h4>
<p>Now, let’s apply the syntax to our actual dataset, <code>df_psycho</code>. We will store the results into the variable <code>anova_one</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>anova_one <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="at">id =</span> <span class="st">"Participant_ID"</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dv =</span> <span class="st">"Neuroticism"</span>, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">between =</span> <span class="st">"Treatment"</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">es =</span> <span class="st">"pes"</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">type =</span> <span class="dv">3</span>, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">include_aov =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> df_psycho) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Converting to factor: Treatment</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Contrasts set to contr.sum for the following variables: Treatment</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova_one)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: Neuroticism
          num Df den Df    MSE      F     ges    Pr(&gt;F)    
Treatment      2     57 85.046 9.0482 0.24097 0.0003866 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We can see that the main effect of <code>Treatment</code> on <code>Neuroticism</code> scores was statistically significant (F(2, 57) = 9.05, p &lt; 0.001). This indicates that there are significant differences in Neuroticism scores among the treatment groups. The effect size (partial eta-squared - under the <code>ges</code> column) is 0.241, which suggests that approximately 24.1% of the variance in Neuroticism scores can be attributed to the differences in treatment groups.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Why does it say `Converting to factor: Treatment'?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why does it say `Converting to factor: Treatment’?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Factors are a special data type in R. They enable R to identify categorical variables like:</p>
<ul>
<li><p>Nationality (levels: Irish, English, Indian, American, French, German, Brazilian)</p></li>
<li><p>Handiness (e.g.&nbsp;right-handed, left-handed, ambi-dextrous)</p></li>
<li><p>Experimental Group (e.g.&nbsp;intervention, control)</p></li>
<li><p>Education Status (e.g.&nbsp;first-year, second-year, third-year, fourth-year, masters, PhD).</p></li>
</ul>
<p>In this case, the <code>aov_ez</code> function is just converting our Treatment variable into a factor/categorical variable, which is what we want!</p>
<p>Factors are really useful when it comes to data manipulation or data wrangling. But we’ll get to that in the last week of the semester.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Effect size cut-off points">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Effect size cut-off points
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>η² = 0.01 represents a small effect</p>
<p>η² = 0.06 represents a medium effect</p>
<p>η² = 0.14 represents a large effect (Richardson, 2011)</p>
</div>
</div>
</div>
</section>
</section>
<section id="step-4-check-parametric-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="step-4-check-parametric-assumptions">Step 4: Check Parametric Assumptions</h3>
<p>Before interpreting our ANOVA results, we need to check whether the test’s assumptions are met. Since these assumptions relate to how well the ANOVA models the data, we <em>evaluate them after running the test</em> rather than before.</p>
<p><strong>Assumptions of a One-Way Between-Subjects ANOVA</strong></p>
<ol type="1">
<li>The dependent variable (DV) is measured on an <em>interval</em> or <em>ratio</em> scale.<br>
</li>
<li>Observations are <em>independent</em> (i.e., no repeated measures).<br>
</li>
<li>The <em>residuals</em> should be <strong>normally distributed</strong>.<br>
</li>
<li>There should be <em>homogeneity of variance</em> between groups.</li>
</ol>
<p>We have already confirmed <strong>Assumption 1</strong> (Neuroticism is ratio data) and <strong>Assumption 2</strong> (each participant is in only one group, ensuring independence).</p>
<p>Now, let’s check the remaining assumptions.</p>
<p><strong>Checking Normality of Residuals</strong></p>
<p>To verify normality, we will:<br>
- <strong>Visualise</strong> residuals with a Q-Q plot.<br>
- <strong>Run the Shapiro-Wilk test</strong> (<code>p &gt; .05</code> indicates normality).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(<span class="fu">residuals</span>(anova_one))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/One-Way%20ANOVA%20assumptions-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18 44</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(anova_one))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(anova_one)
W = 0.99284, p-value = 0.9791</code></pre>
</div>
</div>
<section id="interpreting-the-results" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-results"><strong>Interpreting the Results</strong></h4>
<ul>
<li><p>In the <strong>Q-Q plot</strong>, the dots should closely follow the diagonal line.</p></li>
<li><p>In the <strong>Shapiro-Wilk test</strong>, a <em>p-value greater than .05</em> suggests that residuals are <strong>normally distributed</strong>.</p></li>
</ul>
<p>Since our p-value is <strong>greater than .05 (p &gt; .05)</strong>, normality is <strong>not violated</strong>.</p>
<p><strong>Checking Homoegeneity of Variance</strong></p>
<p>We test whether all groups have similar variance using <strong>Levene’s Test</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_levene</span>(anova_one)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Functionality has moved to the 'performance' package.
Calling 'performance::check_homogeneity()'.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: There is not clear evidence for different variances across groups (Levene's Test, p = 0.965).</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results-1" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-results-1"><strong>Interpreting the Results</strong></h4>
<ul>
<li><p>If the <em>p-value is greater than .05</em>, it means <strong>variance is equal across groups</strong>, satisfying the assumption.</p></li>
<li><p>We have met this assumption!</p></li>
</ul>
</section>
</section>
<section id="step-5-running-post-hoc-tests" class="level3">
<h3 class="anchored" data-anchor-id="step-5-running-post-hoc-tests">Step 5: Running post-hoc tests</h3>
<p>An ANOVA tells us <strong>whether</strong> there is a significant difference between three or more groups, but it does not tell us <strong>where</strong> those differences lie.</p>
<p>If we find a significant result, the next step is to run a <em>post-hoc test</em>, which compares each group to every other group to identify the specific differences.</p>
<section id="post-hoc-test-syntax" class="level4">
<h4 class="anchored" data-anchor-id="post-hoc-test-syntax"><strong>Post-Hoc Test Syntax</strong></h4>
<p>To perform pairwise comparisons, we use the <code>emmeans()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(our_anova_model, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>        pairwise <span class="sc">~</span> IV, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">adjust =</span> <span class="st">"Tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Breaking Down the Code</strong></p>
<ol type="1">
<li><p><strong><code>emmeans(...)</code></strong>: Computes pairwise comparisons between groups.</p></li>
<li><p><strong><code>our_anova_model</code></strong> The variable containing the results of the one-way ANOVA.</p></li>
<li><p><strong><code>pairwise ~ IV</code></strong> Specifies that we want to compare the levels/groups of the independent variable.</p></li>
<li><p><strong><code>adjust = "Tukey"</code></strong> Applies the Tukey correction to adjust p-values for multiple comparisons.</p></li>
</ol>
<p><strong>Why Use the Tukey Correction?</strong></p>
<p>When conducting multiple comparisons, the risk of making a Type I error (false positive) increases. The Tukey correction reduces this risk by adjusting p-values to be more conservative. There are other types of corrections we can apply, but for this class we will stick with Tukey.</p>
</section>
<section id="running-the-post-hoc-test-on-our-data" class="level4">
<h4 class="anchored" data-anchor-id="running-the-post-hoc-test-on-our-data">Running the Post-Hoc Test on Our Data</h4>
<p>We now apply this test to our dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>AOV1_pairwise <span class="ot">&lt;-</span><span class="fu">emmeans</span>(anova_one, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                        pairwise <span class="sc">~</span> Treatment, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">adjust =</span> <span class="st">"Tukey"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>AOV1_pairwise</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Treatment  emmean   SE df lower.CL upper.CL
 DMT          44.5 2.06 57     40.4     48.6
 Placebo      46.4 2.06 57     42.3     50.5
 Psilocybin   56.1 2.06 57     51.9     60.2

Confidence level used: 0.95 

$contrasts
 contrast             estimate   SE df t.ratio p.value
 DMT - Placebo           -1.93 2.92 57  -0.661  0.7867
 DMT - Psilocybin       -11.58 2.92 57  -3.970  0.0006
 Placebo - Psilocybin    -9.65 2.92 57  -3.309  0.0046

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p><strong>Interpreting the Results</strong></p>
<p>The output shows the <strong>p-values</strong> for pairwise comparisons between treatment groups:</p>
<ul>
<li><p><strong>DMT vs.&nbsp;Psilocybin:</strong> <em>p &lt; .001</em> (significant difference)</p></li>
<li><p><strong>Placebo vs.&nbsp;Psilocybin:</strong> <em>p = .005</em> (significant difference)</p></li>
<li><p><strong>DMT vs.&nbsp;Placebo:</strong> <em>p = .787</em> (no significant difference)</p></li>
</ul>
<p>This means that <em>participants who took Psilocybin had significantly higher Neuroticism scores</em> than those in the <strong>Placebo</strong> or <strong>DMT</strong> groups. However, there was <em>no significant difference</em> between the <strong>DMT and Placebo</strong> groups.</p>
</section>
</section>
<section id="step-6-writing-our-results-in-apa-style" class="level3">
<h3 class="anchored" data-anchor-id="step-6-writing-our-results-in-apa-style">Step 6: Writing our results in APA style</h3>
<p>A one-way between-subjects ANOVA was conducted to examine the effect of treatment condition (<em>Placebo</em>, <em>Psilocybin</em>, <em>DMT</em>) on Neuroticism scores. This test was selected as the dependent variable was continuous, there was independence of observations, there was homogeneity of variance, and normality of residuals was displayed.</p>
<p>The analysis revealed a significant effect of treatment on Neuroticism, <em>F</em>(2, 57) = 9.05, <em>p</em> &lt; .001, <em>η²</em> = .241. This suggests that approximately 24.1% of the variance in Neuroticism scores can be attributed to differences between treatment groups. Based on this result, one can reject the null hypothesis.</p>
<p>Post-hoc pairwise comparisons, using the Tukey correction, revealed that:</p>
<p>The <em>Psilocybin</em> group had significantly higher Neuroticism scores than the <em>DMT</em> group (<em>t</em> = -3.97, <em>p</em> = .0006).</p>
<p>The <em>Psilocybin</em> group also had significantly higher Neuroticism scores than the <em>Placebo</em> group (<em>t</em> = -3.31, <em>p</em> = .0046).</p>
<p>No significant difference was found between the <em>DMT</em> and <em>Placebo</em> groups (<em>t</em> = -0.66, <em>p</em> = .787).</p>
<p>These results suggest that <em>Psilocybin</em> led to significantly higher Neuroticism scores compared to <em>DMT</em> and <em>Placebo</em>, while <em>DMT</em> and <em>Placebo</em> did not differ significantly. Based on these results, one can reject the null hypothesis.</p>
</section>
<section id="step-7-power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="step-7-power-analysis">Step 7: Power Analysis</h3>
<p>A <strong>power analysis</strong> helps determine whether our sample size is sufficient to detect an effect. There are <strong>two types of power analysis</strong>:</p>
<ol type="1">
<li><strong>Apriori power analysis</strong> – Performed <em>before</em> data collection to determine the required sample size.<br>
</li>
<li><strong>Post-hoc power analysis</strong> – Performed <em>after</em> an analysis to check how much power the study had given the sample size used.</li>
</ol>
<section id="apriori-power-analysis" class="level4">
<h4 class="anchored" data-anchor-id="apriori-power-analysis"><strong>Apriori Power Analysis</strong></h4>
<p>This test helps us determine the <strong>minimum sample size</strong> needed to achieve <strong>80% power</strong> (<em>power = 0.8</em>), assuming a <strong>moderate effect size</strong> (<em>f = 0.25</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.anova.test</span>(<span class="at">k =</span> <span class="dv">3</span>,  <span class="co"># Number of groups </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">f =</span> .<span class="dv">25</span>, <span class="co"># Expected effect size</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">sig.level =</span> .<span class="dv">05</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">power =</span> .<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Balanced one-way analysis of variance power calculation 

              k = 3
              n = 52.3966
              f = 0.25
      sig.level = 0.05
          power = 0.8

NOTE: n is number in each group</code></pre>
</div>
</div>
<p>This function calculates the required sample size per group to detect an effect. If the calculated sample size is larger than what we collected, it suggests that our study may be underpowered.</p>
</section>
<section id="post-hoc-power-analysis" class="level4">
<h4 class="anchored" data-anchor-id="post-hoc-power-analysis">Post-Hoc Power Analysis</h4>
<p>This test calculates how much power we had given our actual sample size (n = 20 per group).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.anova.test</span>(<span class="at">k =</span> <span class="dv">3</span>, <span class="co">#number of groups </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">n =</span> <span class="dv">20</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">f =</span> .<span class="dv">25</span>, <span class="co">#observed effect size</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">sig.level =</span> .<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Balanced one-way analysis of variance power calculation 

              k = 3
              n = 20
              f = 0.25
      sig.level = 0.05
          power = 0.3744311

NOTE: n is number in each group</code></pre>
</div>
</div>
<p>If the resulting power is above 0.8, the study had sufficient power to detect the expected effect. If it is below 0.8, there is a higher risk of a Type II error (failing to detect a real effect).</p>
<p>We can see that our power is 0.35 (35%), which suggests it is substantially underpowered (we want it to be 80% or higher). Therefore we need to be extra cautious when interpreting these results.</p>
</section>
</section>
<section id="step-8-create-a-nice-visualisation-violin-plot" class="level3">
<h3 class="anchored" data-anchor-id="step-8-create-a-nice-visualisation-violin-plot">Step 8: Create a Nice Visualisation (Violin Plot)</h3>
<p>Next week we will go into more detail on how to create nice visualisations in R. But here is code that you can use in the meantime to create a violin plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_psycho, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> Neuroticism, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">fill =</span> Treatment)) <span class="sc">+</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Effect of Psychoactive Treatment on Neuroticism"</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> .<span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The main thing, is that when you are adapting this code for your own work (e.g.&nbsp;in the exercise later), make sure to replace wherever you see <code>Treatment</code> with your Independent Variable, and where ever you see <code>Neuroticism</code> with your Dependent Variable. Don’t forgot to change the title as well! E</p>
<p>We will visualise the results of a Factorial ANOVA in a different way, but more on that later.</p>
</section>
</section>
<section id="activity-5-one-way-anova-exercise" class="level2">
<h2 class="anchored" data-anchor-id="activity-5-one-way-anova-exercise">Activity 5: One-Way ANOVA Exercise</h2>
<p>Researchers investigated the effects of caffeine consumption on mood.</p>
<p><strong>Research Question</strong>: Is there an effect of Caffeine on Mood?</p>
<p><strong>Hypotheses</strong>:</p>
<p><em>H₀ (Null Hypothesis):</em> There is no effect of Caffeine on Mood?</p>
<p><em>H₁ (Alternative Hypothesis)</em>: There is an effect of Caffeine on Mood.</p>
<p><strong>Method</strong>: 200 participants were randomly assigned to one of four groups for one week: No Caffeine (Control), 100mg of Caffeine (Low Caffeine), 250mg of Caffeine (High Caffeine), or 400mg of Caffeine (High Caffeine). Their mood was collected each day and an average of their mood scores for the week was computed.</p>
<p><strong><em>Our task</em></strong>: Run a One-Way ANOVA to see if there is an effect of Caffeine on Mood.</p>
<p>Follow the same <strong>seven steps</strong> from the worked example to analyse this dataset.</p>
<ol type="1">
<li><p><strong>Load and Inspect the Dataset</strong></p>
<ul>
<li><p>Load the dataset (<code>caffeine_mood.csv</code>) into R.</p></li>
<li><p>Check the first few rows using <code>head()</code>.</p></li>
</ul></li>
<li><p><strong>Explore the Data</strong></p>
<ul>
<li><p>Calculate descriptive statistics for <code>mood</code> split by by <code>group</code>.</p></li>
<li><p>Create visualisations: histograms with density plots, barplots, and a boxplot.</p></li>
</ul></li>
<li><p><strong>Run the One-Way ANOVA</strong></p>
<ul>
<li>Use <code>aov_ez()</code> to perform the ANOVA.</li>
</ul></li>
<li><p><strong>Check ANOVA Assumptions</strong></p>
<ul>
<li><p>Test normality of residuals with a <strong>Q-Q plot</strong> and <strong>Shapiro-Wilk test</strong>.</p></li>
<li><p>Check homogeneity of variance using <strong>Levene’s test</strong>.</p></li>
<li><p>If there are violations, just make a note of them.</p></li>
</ul></li>
<li><p><strong>Conduct Post-Hoc Comparisons</strong></p>
<ul>
<li>Use <code>emmeans()</code> with Tukey correction to determine which specifc groups are significantly different.</li>
</ul></li>
<li><p><strong>Report Results in APA Format</strong></p>
<ul>
<li>Write a short APA-style interpretation of the results.</li>
</ul></li>
<li><p><strong>Conduct a Power Analysis</strong></p>
<ul>
<li>Use <code>pwr.anova.test()</code> to check <strong><em>post-hoc</em></strong> statistical power.</li>
</ul></li>
</ol>
</section>
</section>
<section id="factorial-anova" class="level1">
<h1>Factorial ANOVA</h1>
<section id="activity-6-factorial-anova-example" class="level2">
<h2 class="anchored" data-anchor-id="activity-6-factorial-anova-example">Activity 6: Factorial ANOVA Example</h2>
<p>One-Way ANOVAS are a good test when you are investigating the effect of one independent variable with three or more levels on some dependent variable. However, you will often want to investigate the effect of more than one independent variable on a dependent variable. In those situations, Factorial ANOVAS can be an excellent statistical test to use.</p>
<p>In this example, we will walk through the steps involved in conducting a Factorial ANOVA.</p>
<section id="research-introduction" class="level3">
<h3 class="anchored" data-anchor-id="research-introduction">Research Introduction</h3>
<p>In recent years, psychological interventions such as Cognitive Behavioral Therapy (CBT), Dialectical Behavioural Therapy (DBT) and Mindfulness-Based Therapy have gained widespread recognition for their effectiveness in treating anxiety. While both therapies have been shown to reduce anxiety, their relative effectiveness and their effectiveness over different durations of interventions are still of interest. This study aimed to investigate the effect of therapy type (CBT, Mindfulness, or no intervention) on anxiety reduction over different durations of time.</p>
<p><strong>Research Question:</strong> Is there an effect of therapy type and duration of treatment on anxiety?</p>
<p><strong>Hypotheses:</strong></p>
<p><em>Null Hypothesis (H₀)</em><strong>:</strong> Therapy type and treatment duration have no effect on anxiety levels after the intervention.</p>
<p><em>Alternative Hypothesis (H₁)</em><strong>:</strong> Therapy type and treatment duration influence anxiety levels, with CBT and DBT leading to lower anxiety scores compared to Mindfulness, and longer durations (12 weeks) resulting in greater anxiety reduction than shorter durations (6 weeks).</p>
<p><strong>Method</strong>: A total of 180 participants were randomly assigned to one of three therapy groups: CBT (n = 60), DBT (n = 60), or Mindfulness (n = 60). They were also randomly assigned to receive therapy for either 6 weeks (n = 90) or 12 weeks (n = 90). After completing the assigned intervention, their anxiety levels were measured.</p>
<p><strong>Analysis Plan:</strong> A <em>3×2 Factorial ANOVA</em> will be conducted to examine:</p>
<ol type="1">
<li><p>The <strong>main effect of therapy type</strong> (whether different therapies lead to different anxiety levels).</p></li>
<li><p>The <strong>main effect of duration</strong> (whether 6-week vs.&nbsp;12-week treatment impacts anxiety levels differently).</p></li>
<li><p>The <strong>interaction effect</strong> between therapy type and duration (whether the effectiveness of a therapy depends on the length of treatment).</p></li>
</ol>
<p>This approach allows us to understand both the individual and combined effects of therapy type and duration on anxiety reduction.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Why is it a 3X2 Factorial ANOVA?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why is it a 3X2 Factorial ANOVA?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I used to often get confused about the numbers for a factorial design. For example, why is this called a 3x2 Factorial ANOVA?</p>
<p>Well the reason is that this examines the effects of two independent variables, each with multiple levels:</p>
<ol type="1">
<li><p><strong>Therapy Type</strong> (Independent Variable 1) – This variable has <strong>three levels</strong>:</p>
<ul>
<li><p>Cognitive Behavioral Therapy (CBT)</p></li>
<li><p>Mindfulness-Based Therapy</p></li>
<li><p>Dialectical Behavioural Therapy (DBT)</p></li>
</ul></li>
<li><p><strong>Duration</strong> (Independent Variable 2) – This variable has <strong>two levels</strong>:</p>
<ul>
<li><p>6 weeks of treatment</p></li>
<li><p>12 weeks of treatment</p></li>
</ul></li>
</ol>
<p>Since the first independent variable (<strong>Therapy Type</strong>) has <strong>3 levels</strong> and the second independent variable (<strong>Duration</strong>) has <strong>2 levels</strong>, the appropriate notation for this design is <strong>3×2</strong>.</p>
</div>
</div>
</div>
</section>
<section id="step-1-load-in-and-check-your-data" class="level3">
<h3 class="anchored" data-anchor-id="step-1-load-in-and-check-your-data">Step 1: Load in and Check Your Data</h3>
<p>First, we need to load the dataset into R using the <code>read.csv()</code> function. Let’s call it <code>df_anxiety</code>. We can then check the first six rows using the <code>head()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df_anxiety <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"anxiety_treatment.csv"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_anxiety)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID  Anxiety     Therapy Duration
1  1 54.63603 Mindfulness  6 Weeks
2  2 76.04019 Mindfulness  6 Weeks
3  3 58.30279 Mindfulness  6 Weeks
4  4 58.55996 Mindfulness  6 Weeks
5  5 51.01651 Mindfulness  6 Weeks
6  6 63.09393 Mindfulness  6 Weeks</code></pre>
</div>
</div>
<p>One step we are going to do extra here is turn the</p>
</section>
<section id="step-2-conduct-descriptive-statistical-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="step-2-conduct-descriptive-statistical-analysis-1">Step 2: Conduct Descriptive Statistical Analysis</h3>
<p>Now, let’s run some descriptive statistics using the <code>descriptives()</code> function. This will help us understand the distribution of <strong>Anxiety</strong> scores across the different Treatment and Duration groups.</p>
<p>We will first calculate the mean, standard deviation, and other key statistics for Anxiety , grouped by Treatment. We will also generate</p>
<ul>
<li><p>A histogram (<code>hist = TRUE</code>) with a density overlay (<code>dens = TRUE</code>).</p></li>
<li><p>A bar plot (<code>bar = TRUE</code>).</p></li>
<li><p>A boxplot (<code>box = TRUE</code>) to examine distribution and possible outliers.</p></li>
</ul>
<p>We are also going to convert the <strong>Duration</strong> variable into a factor. You do not need to include this code in the exercise, as we have not covered factors yet. However, I am doing it here to ensure that any plots display 6 weeks first and then 12 weeks afterwards.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df_anxiety<span class="sc">$</span>Duration <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_anxiety<span class="sc">$</span>Duration, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"6 Weeks"</span>, <span class="st">"12 Weeks"</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_anxiety,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">vars =</span> Anxiety,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="fu">c</span>(<span class="st">"Therapy"</span>, <span class="st">"Duration"</span>),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">min =</span> F,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">max =</span> F,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">box =</span> T,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">hist =</span> T,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">bar =</span> T,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">dens =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in FUN(X[[i]], ...): no non-missing arguments to max; returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                                  
 ───────────────────────────────────────────────────────────── 
                         Therapy        Duration    Anxiety    
 ───────────────────────────────────────────────────────────── 
   N                     CBT            6 Weeks           30   
                                        12 Weeks          30   
                         DBT            6 Weeks           30   
                                        12 Weeks          30   
                         Mindfulness    6 Weeks           30   
                                        12 Weeks          30   
   Missing               CBT            6 Weeks            0   
                                        12 Weeks           0   
                         DBT            6 Weeks            0   
                                        12 Weeks           0   
                         Mindfulness    6 Weeks            0   
                                        12 Weeks           0   
   Mean                  CBT            6 Weeks     50.72652   
                                        12 Weeks    40.61220   
                         DBT            6 Weeks     47.76104   
                                        12 Weeks    38.54935   
                         Mindfulness    6 Weeks     63.94147   
                                        12 Weeks    59.69312   
   Median                CBT            6 Weeks     49.93308   
                                        12 Weeks    40.43544   
                         DBT            6 Weeks     47.70946   
                                        12 Weeks    38.58374   
                         Mindfulness    6 Weeks     63.36728   
                                        12 Weeks    59.45626   
   Standard deviation    CBT            6 Weeks     6.241643   
                                        12 Weeks    6.144259   
                         DBT            6 Weeks     7.812456   
                                        12 Weeks    6.536182   
                         Mindfulness    6 Weeks     6.140044   
                                        12 Weeks    6.217064   
 ───────────────────────────────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the results, we can observe the following:</p>
<ul>
<li><p>Participants who completed CBT and DBT therapy had lower Anxiety scores than participants who completed Mindfulness therapy.</p></li>
<li><p>Participants who completed 12-weeks of therapy had lower Anxiety scores than participants who completed six-weeks of therapy.</p></li>
<li><p>There does not seem to much difference between participants who completed DBT and CBT, although it seems like participants who completed DBT had slightly smaller Anxiety scores.</p></li>
<li><p>The bar plot identifies one outlier in the Mindfulness - Six Weeks group. The ANOVA is generally robust to single outliers, so we can ignore this for now.</p></li>
</ul>
<p>Now let’s investigate whether there is a significant effect of Therapy on Anxiety over Length.</p>
</section>
<section id="step-3-run-your-factorial-anova" class="level3">
<h3 class="anchored" data-anchor-id="step-3-run-your-factorial-anova">Step 3: Run Your Factorial ANOVA</h3>
<section id="the-syntax" class="level4">
<h4 class="anchored" data-anchor-id="the-syntax">The Syntax</h4>
<p>To run a <strong>factorial ANOVA</strong>, we also use the&nbsp;<code>aov_ez()</code>&nbsp;function. The syntax is nearly identical to the One-Way ANOVA.</p>
<p>Below is the general syntax (remember you will need to replace certain placeholders with the appropriate column names from your dataset):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>anova_example_syntax <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="at">id =</span> <span class="st">"The name of the Participant ID column"</span>,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dv =</span> <span class="st">"The name of the dependent variable"</span>, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">between =</span> <span class="st">"The name(s) of the between-subjects independent variable"</span>, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">es =</span> <span class="st">"pes"</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">type =</span> <span class="dv">3</span>, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">include_aov =</span> <span class="cn">TRUE</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> yourdataset) </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova_example_syntax) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="running-it-on-our-dataset" class="level4">
<h4 class="anchored" data-anchor-id="running-it-on-our-dataset">Running it on our Dataset</h4>
<p>For our dataset, we have two between subjects independent variables: <code>Therapy</code> and <code>Duration</code>, so our code will be the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fact_anova <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="at">id =</span> <span class="st">"ID"</span>,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">between =</span> <span class="fu">c</span>(<span class="st">"Therapy"</span>, <span class="st">"Duration"</span>), </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">dv =</span> <span class="st">"Anxiety"</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">es =</span> <span class="st">"pes"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">include_aov =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> df_anxiety) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Converting to factor: Therapy</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Contrasts set to contr.sum for the following variables: Therapy, Duration</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>fact_output <span class="ot">&lt;-</span> <span class="fu">summary</span>(fact_anova)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>fact_output</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: Anxiety
                 num Df den Df    MSE        F     ges                Pr(&gt;F)
Therapy               2    174 42.803 143.7634 0.62299 &lt; 0.00000000000000022
Duration              1    174 42.803  64.9195 0.27172    0.0000000000001195
Therapy:Duration      2    174 42.803   3.4962 0.03863               0.03246
                    
Therapy          ***
Duration         ***
Therapy:Duration *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We can see that the main effect of Therapy type on Anxiety scores was statistically significant, F(2, 174) = 143.76, p &lt; 0.001. This indicates that different therapy types led to significantly different anxiety levels after the intervention. The effect size (generalised eta squared) is 0.623, suggesting that approximately 62.3% of the variance in anxiety scores can be attributed to differences in therapy type.</p>
<p>The main effect of Duration was also statistically significant, F(1, 174) = 64.92, p &lt; 0.001, indicating that treatment length (6 weeks vs.&nbsp;12 weeks) had a significant impact on anxiety levels. The effect size is 0.272, meaning that 27.2% of the variance in anxiety scores is explained by treatment duration.</p>
<p>Additionally, there was a significant interaction effect between Therapy type and Duration, F(2, 174) = 3.50, p = 0.032. The effect size is 0.039, indicating that the interaction accounts for 3.9% of the variance in anxiety scores. This suggests that the effectiveness of therapy types may depend on the duration of treatment.</p>
</section>
</section>
<section id="step-4-check-your-parametric-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="step-4-check-your-parametric-assumptions">Step 4: Check Your Parametric Assumptions</h3>
<p>Before interpreting our ANOVA results, we need to check whether the test’s assumptions are met. Since these assumptions relate to how well the ANOVA models the data, we evaluate them after running the test rather than before.</p>
<p><strong>Assumptions of a Factorial ANOVA</strong></p>
<p>The assumptions are the same as one the one-way ANOVA, namely:</p>
<ol type="1">
<li><p>The dependent variable (DV) is measured on an <em>interval</em> or <em>ratio</em> scale.</p></li>
<li><p>Observations are <em>independent</em> (i.e., no repeated measures).</p></li>
<li><p>The <em>residuals</em> should be <strong>normally distributed</strong>.</p></li>
<li><p>There should be <em>homogeneity of variance</em> between groups.</p></li>
</ol>
<p>A basic glance at the data already confirms <strong>Assumption 1</strong> (Anxiety is interval data) and <strong>Assumption 2</strong> (each participant is in only one group, ensuring independence).</p>
<p>We can use the same method as before to check normality of residuals and homogeneity of variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Normality Assumption</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(<span class="fu">residuals</span>(fact_anova))  <span class="co"># Q-Q Plot of residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  68 128</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(fact_anova))  <span class="co"># Shapiro-Wilk test for normality</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(fact_anova)
W = 0.99368, p-value = 0.6344</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Homogeneity of Variance</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">test_levene</span>(fact_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Functionality has moved to the 'performance' package.
Calling 'performance::check_homogeneity()'.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: There is not clear evidence for different variances across groups (Levene's Test, p = 0.352).</code></pre>
</div>
</div>
<p>We can see that the dots are mostly on the line. The Shapiro-Wilk’s value is greater than .05, as is the Levene’s Test p-value. Based on these results, we can say we have met our assumptions.</p>
<p>Now let’s determine where the differences lie!</p>
</section>
<section id="step-5-run-your-post-hoc-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="step-5-run-your-post-hoc-comparisons">Step 5: Run Your Post-Hoc Comparisons</h3>
<p>Like the One-Way ANOVA, a factorial ANOVA tells us whether there is a significant difference between three or more groups, but it does not tell us where those differences lie.</p>
<p>If we find a significant result, the next step is to run a post-hoc test, which compares each group to every other group to identify the specific differences.</p>
<p>The syntax is slightly different for the Factorial ANOVA. The reason for this is that we are comparing differences in groups across more than one independent variables. So we will need post-hoc tests across both Therapy Type and Duration of Therapy.</p>
<p>Luckily, it is easy to do this in R using the <code>|</code> symbol.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>posthoc_factorial <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(fact_anova, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                             pairwise <span class="sc">~</span> Therapy <span class="sc">|</span> Duration, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">adjust =</span> <span class="st">"Tukey"</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>posthoc_factorial</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
Duration = 6 Weeks:
 Therapy     emmean   SE  df lower.CL upper.CL
 CBT           50.7 1.19 174     48.4     53.1
 DBT           47.8 1.19 174     45.4     50.1
 Mindfulness   63.9 1.19 174     61.6     66.3

Duration = 12 Weeks:
 Therapy     emmean   SE  df lower.CL upper.CL
 CBT           40.6 1.19 174     38.3     43.0
 DBT           38.5 1.19 174     36.2     40.9
 Mindfulness   59.7 1.19 174     57.3     62.1

Confidence level used: 0.95 

$contrasts
Duration = 6 Weeks:
 contrast          estimate   SE  df t.ratio p.value
 CBT - DBT             2.97 1.69 174   1.756  0.1878
 CBT - Mindfulness   -13.21 1.69 174  -7.823  &lt;.0001
 DBT - Mindfulness   -16.18 1.69 174  -9.579  &lt;.0001

Duration = 12 Weeks:
 contrast          estimate   SE  df t.ratio p.value
 CBT - DBT             2.06 1.69 174   1.221  0.4423
 CBT - Mindfulness   -19.08 1.69 174 -11.296  &lt;.0001
 DBT - Mindfulness   -21.14 1.69 174 -12.517  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p><strong><em>Interpreting the Results</em></strong></p>
<section id="main-findings" class="level4">
<h4 class="anchored" data-anchor-id="main-findings"><strong>Main Findings</strong></h4>
<ol type="1">
<li><p><strong>12-Week Duration</strong>:</p>
<ul>
<li><p>CBT (M = 40.6) and DBT (M = 38.5) resulted in lower anxiety scores than Mindfulness (M = 59.7).</p></li>
<li><p>The difference between CBT and DBT was small and not statistically significant (p = 0.671).</p></li>
<li><p>Mindfulness had significantly higher anxiety scores compared to both CBT (p &lt; .0001) and DBT (p &lt; .0001), suggesting that CBT and DBT were more effective in reducing anxiety over 12 weeks.</p></li>
</ul></li>
<li><p><strong>6-Week Duration</strong>:</p>
<ul>
<li><p>CBT (M = 50.7) and DBT (M = 47.8) again showed lower anxiety scores than Mindfulness (M = 63.9).</p></li>
<li><p>The difference between CBT and DBT was not significant (p = 0.2428).</p></li>
<li><p>Mindfulness resulted in significantly higher anxiety scores compared to CBT (p &lt; .0001) and DBT (p &lt; .0001), indicating that it was the least effective therapy type over 6 weeks.</p></li>
</ul></li>
</ol>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary"><strong>Summary</strong></h4>
<ul>
<li><p>CBT and DBT both significantly reduced anxiety compared to Mindfulness at both 6-week and 12-week durations.</p></li>
<li><p>There was no significant difference between CBT and DBT in reducing anxiety.</p></li>
<li><p>The 12-week duration was more effective than 6 weeks, as anxiety scores were lower across all therapy types after 12 weeks.</p></li>
<li><p>The interaction effect suggests that Mindfulness was particularly ineffective over shorter durations, as its scores were much higher than CBT and DBT, especially at 6 weeks.</p></li>
</ul>
<p>Overall, the findings indicate that CBT and DBT are both effective therapies for reducing anxiety, especially over 12 weeks, whereas Mindfulness is less effective in comparison.</p>
</section>
</section>
<section id="step-6-visualise-your-model" class="level3">
<h3 class="anchored" data-anchor-id="step-6-visualise-your-model">Step 6: Visualise your Model</h3>
<p>The following code will enable us to plot the interaction between Duration and Therapy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">afex_plot</span>(fact_anova, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Duration"</span>, <span class="co">#what goes on the x-axis</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">trace =</span> <span class="st">"Therapy"</span>, <span class="co">#to make sure it tracks the other independent variable as well</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">error =</span> <span class="st">"between"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">mapping =</span> <span class="fu">c</span>(<span class="st">"color"</span>, <span class="st">"linetype"</span>)) <span class="sc">+</span>  <span class="co"># Automatically maps color &amp; line type to Therapy</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()  <span class="co"># Clean and simple theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-workshop-activities_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When adapting this code to your own work, make sure to replace <code>Duration</code> and <code>Therapy</code> with your own Independent Variables.</p>
<p>In terms of deciding what goes on the x-axis, it does not really matter too much. You could swap Duration and Therapy in the above code, and it will still produce a plot (feel free to try). Usually, the final decision is what plot looks more informative about the results.</p>
</section>
<section id="step-7-write-up-your-results-in-apa-style" class="level3">
<h3 class="anchored" data-anchor-id="step-7-write-up-your-results-in-apa-style">Step 7: Write up your results in APA style</h3>
<p>A 3 × 2 factorial ANOVA was conducted to examine the effects of therapy type (<em>CBT</em>, <em>DBT</em>, <em>Mindfulness</em>) and treatment duration (6 weeks vs.&nbsp;12 weeks) on post-treatment anxiety scores.</p>
<p>There was a significant main effect of therapy type, <em>F</em>(2, 174) = 143.76, <em>p</em> &lt; .001, <em>η²ₚ</em> = 0.623, indicating that anxiety scores differed significantly across therapy conditions.</p>
<p>There was also a significant main effect of treatment duration, <em>F</em>(1, 174) = 64.92, <em>p</em> &lt; .001, <em>η²ₚ</em> = 0.272, suggesting that participants who received 12 weeks of treatment (<em>M</em> = 46.3, <em>SE</em> = 1.19) had significantly lower anxiety scores than those who received 6 weeks of treatment (<em>M</em> = 54.1, <em>SE</em> = 1.19).</p>
<p>The therapy type by treatment duration interaction was also statistically significant, <em>F</em>(2, 174) = 3.50, <em>p</em> = .032, <em>η²ₚ</em> = 0.039, indicating that the effectiveness of therapy type depended on treatment duration.</p>
<p>Post-hoc comparisons with Tukey correction showed that <em>CBT</em> (<em>M</em> = 50.7, <em>SE</em> = 1.19) and <em>DBT</em> (<em>M</em> = 47.8, <em>SE</em> = 1.19) were significantly more effective than <em>Mindfulness</em> (<em>M</em> = 63.9, <em>SE</em> = 1.19) at reducing anxiety after 6 weeks (<em>p</em> &lt; .0001). Similarly, after 12 weeks, <em>CBT</em> (<em>M</em> = 40.6, <em>SE</em> = 1.19) and <em>DBT</em> (<em>M</em> = 38.5, <em>SE</em> = 1.19) remained significantly more effective than <em>Mindfulness</em> (<em>M</em> = 59.7, <em>SE</em> = 1.19) (<em>p</em> &lt; .0001). However, there was no significant difference between <em>CBT</em> and <em>DBT</em> at either time point (<em>p</em> = .671 for 12 weeks; <em>p</em> = .243 for 6 weeks).</p>
<p>Based on these results, one can reject the null hypothesis.</p>
</section>
</section>
<section id="activity-7-factorial-anova-exercise" class="level2">
<h2 class="anchored" data-anchor-id="activity-7-factorial-anova-exercise">Activity 7: Factorial ANOVA Exercise</h2>
<section id="research-introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="research-introduction-1"><strong>Research Introduction</strong></h3>
<p>Obesity is a growing health concern, and many people try different exercise and diet strategies to lose weight. However, it is unclear how different types of exercise and diets affect weight loss. This study aims to investigate the impact of <strong>exercise type</strong> (Three Levels: <em>None, Cardio, Strength Training</em>) and <strong>diet type</strong> (Two Levels: <em>Standard, High-Protein</em>) on weight loss.</p>
</section>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question"><strong>Research Question</strong></h3>
<p>Is there an effect of exercise type and diet type on weight loss?</p>
</section>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses"><strong>Hypotheses</strong></h3>
<p><em>H₀ (Null Hypothesis):</em> There is no effect of exercise and diet type on weight loss.</p>
<p><em>H₁ (Alternative Hypothesis):</em> There is an effect of exercise and diet type on weight loss.</p>
</section>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method"><strong>Method</strong></h3>
<p>A total of <strong>180 participants</strong> were randomly assigned to one exercise type and one diet type in a <strong>3 × 2 design</strong>:</p>
<ol type="1">
<li><p><strong>Exercise Type:</strong></p>
<ul>
<li><p>None (n = 60)</p></li>
<li><p>Cardio (n = 60_</p></li>
<li><p>Strength Training (n = 60)</p></li>
</ul></li>
<li><p><strong>Diet Type:</strong></p>
<ul>
<li><p>Standard Diet (n = 90)</p></li>
<li><p>High-Protein Diet (n = 90)</p></li>
</ul></li>
</ol>
<p>The study lasted 12 weeks, with participants in the exercise groups attending three supervised sessions per week. Participants followed dietary guidelines based on their assigned diet type. Weight loss (kg) was recorded at the end of the study.</p>
</section>
<section id="our-task" class="level3">
<h3 class="anchored" data-anchor-id="our-task"><strong>Our Task</strong></h3>
<p>Conduct a <strong>factorial ANOVA</strong> to test whether exercise type and diet type effect weight loss and if there is an interaction between them. Use the <code>diet_exercise</code>.csv dataset. Run through the same exact steps as the example.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>